import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { 
    padding: 20, 
    backgroundColor: '#f4f6f8', 
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#222',
    flex: 1,
    marginRight: 12,
  },
  category: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f26522',
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222',
    marginBottom: 4,
  },
  value: {
    fontSize: 16,
    fontWeight: '400',
    color: '#444',
    lineHeight: 24,
  },
  copyButton: {
    marginLeft: 8,
    padding: 4,
    borderRadius: 6,
    backgroundColor: '#eee',
  },
  copyButtonText: {
    fontSize: 16,
  },
  mapContainer: {
    height: 250,
    marginVertical: 16,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  sectionTitle: { 
    fontSize: 20, 
    fontWeight: '700', 
    marginBottom: 12, 
    color: '#1f1f1f', 
    borderBottomWidth: 2, 
    borderBottomColor: '#f26522', 
    paddingBottom: 4,
  },
  card: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    marginBottom: 14,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cardText: { 
    fontSize: 16, 
    fontWeight: '600', 
    marginBottom: 4, 
    color: '#1f1f1f', 
  },
  cardSubText: { 
    fontSize: 13, 
    color: '#888', 
  },
  joinButton: {
    backgroundColor: '#f26522',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    shadowColor: '#f26522',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  joinButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
    textAlign: 'center',
  },
  toggleBtn: {
  fontSize: 14,
  fontWeight: '600',
  color: '#007AFF',
  marginTop: 12,
},
});
