// scripts/build-regions.js
// CSV를 읽어 고정 옵션 모듈(src/data/regions.gen.ts)을 생성합니다.
const fs = require('fs');
const path = require('path');

// 아주 간단한 CSV 파서(쉼표·개행 기준). 큰따옴표/이스케이프 등 복잡한 CSV는 필요 시 papaparse로 교체 가능.
function parseCsv(text) {
  const lines = text.trim().split(/\r?\n/);
  const header = lines[0].split(',');
  const rows = lines.slice(1).map((line) => {
    const cols = line.split(',');
    const obj = {};
    header.forEach((h, i) => { obj[h.trim()] = (cols[i] ?? '').trim(); });
    return obj;
  });
  return rows;
}

(function main() {
  const csvPath = path.resolve(__dirname, '../src/data/regions.csv');
  const outPath = path.resolve(__dirname, '../src/data/regions.gen.ts');

  if (!fs.existsSync(csvPath)) {
    console.error('[build-regions] src/data/regions.csv 파일이 없습니다.');
    process.exit(1);
  }

  const csv = fs.readFileSync(csvPath, 'utf8');
  const rows = parseCsv(csv);

  // province,city → 유니크화
  const provincesSet = new Set();
  const citiesMap = new Map(); // province -> Set(cities)

  rows.forEach(({ province = '', city = '' }) => {
    if (!province) return;
    provincesSet.add(province);

    if (!citiesMap.has(province)) citiesMap.set(province, new Set());
    // city가 비어 있으면 넣지 않음(세종처럼 시/군/구 없음 케이스)
    if (city) citiesMap.get(province).add(city);
  });

  const provinces = Array.from(provincesSet).sort((a, b) => a.localeCompare(b, 'ko'));
  const citiesByProvince = {};
  provinces.forEach((p) => {
    const set = citiesMap.get(p) || new Set();
    const arr = Array.from(set).sort((a, b) => a.localeCompare(b, 'ko'));
    citiesByProvince[p] = arr;
  });

  const file = `/* AUTO-GENERATED by scripts/build-regions.js. Do not edit manually. */
export const PROVINCES = ${JSON.stringify(provinces)} as const;

export const CITIES_BY_PROVINCE: Record<string, string[]> = ${JSON.stringify(citiesByProvince, null, 2)};
`;

  fs.writeFileSync(outPath, file, 'utf8');
  console.log('[build-regions] 생성 완료:', path.relative(process.cwd(), outPath));
})();
